/**
 * @file InteractionHeavyWorld.cpp
 * @author Truong Phan
 * @author Jose Hernandez
 *
 * @brief Implementation of InteractionHeavyWorld, a dungeon world with movement,
 *        resources, inventory management, and combat against hunter/pacing enemies.
 * @note Status: FINAL
 *
 * @citation This world was developed with the help of Claude AI and Copilot. The initial code was
 * generated by Claude, then iteratively refined and expanded by the authors. Refractoring and cleanup
 * was also assisted by Claude. The dungeon layout was designed by the authors using donjon; RPG Tools
 * (https://donjon.bin.sh/) and loaded from a text file.
 */
#include "InteractionHeavyWorld.hpp"
#include "../Agents/GoblinAgent.hpp"
#include "../Agents/HunterAgent.hpp"
#include "../Agents/PacingAgent.hpp"
#include <algorithm>
#include <fstream>
#include <random>
#include <sstream>
#include <array>

namespace cse498
{

    // =============================================================================
    // Construction
    // =============================================================================

    InteractionHeavyWorld::InteractionHeavyWorld()
    {
        SetWorldResourceNames({"HP", "Stone", "Gold"});
        SyncResources();

        ConfigureCellTypes();
        GenerateWorld();
    }

    // =============================================================================
    // WorldBase overrides
    // =============================================================================

    void InteractionHeavyWorld::ConfigAgent(AgentBase &agent)
    {
        agent.AddAction("up", ACTION_MOVE_UP);
        agent.AddAction("down", ACTION_MOVE_DOWN);
        agent.AddAction("left", ACTION_MOVE_LEFT);
        agent.AddAction("right", ACTION_MOVE_RIGHT);
        agent.AddAction("break_boulder", ACTION_BREAK_BOULDER);
        agent.AddAction("collect", ACTION_COLLECT);
        agent.AddAction("pay", ACTION_PAY);
        agent.AddAction("print_inventory", ACTION_PRINT_INVENTORY);
        agent.AddAction("throw_up", ACTION_THROW_UP);
        agent.AddAction("throw_down", ACTION_THROW_DOWN);
        agent.AddAction("throw_left", ACTION_THROW_LEFT);
        agent.AddAction("throw_right", ACTION_THROW_RIGHT);

        if (agent.IsInterface())
        {
            NotifyInterfaceResources(agent);
        }
    }

    // =============================================================================
    // Setup — cell types
    // =============================================================================

    void InteractionHeavyWorld::ConfigureCellTypes()
    {
        // Structure cells
        mWallCellID = main_grid.AddCellType("wall", "Wall cell", '#', false);
        mFloorCellID = main_grid.AddCellType("floor", "Floor cell", ' ', true);
        mExitCellID = main_grid.AddCellType("exit", "Exit", 'X', true);
        mStartCellID = main_grid.AddCellType("start", "Start", 'S', true);

        // Interactive resource cells
        mBoulderCellID = main_grid.AddCellType("boulder", "Boulder resource", 'O', false);
        mChestCellID = main_grid.AddCellType("chest", "Chest resource", 'C', false);

        // Post-interaction cells
        mMaterialCellID = main_grid.AddCellType("material", "Dropped material", 'M', true);
        mChestOpenCellID = main_grid.AddCellType("chest_open", "Opened chest", 'c', false);
    }

    // =============================================================================
    // Setup — dungeon generation
    // =============================================================================

    void InteractionHeavyWorld::GenerateWorld()
    {
        // Note: swap the filename for "DungeonMapSmall.txt" to use the smaller test map.
        std::ifstream file(kDungeonMapFile.data());
        if (!file)
        {
            std::cerr << "Error: Could not open " << kDungeonMapFile << " (ignore if running tests)\n";
            return;
        }

        std::vector<std::string> dungeonLayout;
        std::string line;
        while (std::getline(file, line))
        {
            if (!line.empty() && line.back() == '\r')
            {
                line.pop_back();
            }
            dungeonLayout.push_back(line);
        }

        const size_t width = dungeonLayout[0].size();
        const size_t height = dungeonLayout.size();
        main_grid.Resize(width, height, mFloorCellID);

        LoadDungeon(dungeonLayout);

        // Place boulders randomly on the map, with quantity based on map size.
        if (kDungeonMapFile.find("Small") == std::string_view::npos)
        {
            PlaceBoulders(kLargeMapMinBoulders, kLargeMapMaxBoulders);
        }
        else
        {
            PlaceBoulders(kSmallMapMinBoulders, kSmallMapMaxBoulders);
        }
    }

    void InteractionHeavyWorld::LoadDungeon(const std::vector<std::string> &dungeonLayout)
    {
        mDroppedLoot.clear();
        mHunterSpawnPositions.clear();
        mGoblinSpawnPositions.clear();
        mPacingSpawnPositions.clear();

        for (size_t y = 0; y < dungeonLayout.size(); ++y)
        {
            for (size_t x = 0; x < dungeonLayout[y].size(); ++x)
            {
                const char ch = dungeonLayout[y][x];
                const WorldPosition pos(x, y);

                switch (ch)
                {
                case '#':
                    main_grid[pos] = mWallCellID;
                    break;

                case ' ':
                    main_grid[pos] = mFloorCellID;
                    break;

                case 'X':
                    main_grid[pos] = mExitCellID;
                    mExitPosition = pos;
                    break;

                case 'S':
                    // The start marker is treated as a floor cell at runtime.
                    main_grid[pos] = mFloorCellID;
                    mStartPosition = pos;
                    break;

                case 'C':
                    main_grid[pos] = mChestCellID;
                    break;

                case 'H':
                    // Hunter spawn: treated as floor; position saved for web_main placement.
                    main_grid[pos] = mFloorCellID;
                    mHunterSpawnPositions.push_back(pos);
                    break;

                case 'G':
                    // Goblin spawn: treated as floor; position saved for web_main placement.
                    main_grid[pos] = mFloorCellID;
                    mGoblinSpawnPositions.push_back(pos);
                    break;

                case 'P':
                    // Pacing enemy spawn: treated as floor; position saved for web_main placement.
                    main_grid[pos] = mFloorCellID;
                    mPacingSpawnPositions.push_back(pos);
                    break;

                default:
                    break;
                }
            }
        }
    }

    // =============================================================================
    // Position helpers
    // =============================================================================

    WorldPosition InteractionHeavyWorld::GetStartPosition() const
    {
        return mStartPosition;
    }

    const InteractionHeavyWorld::PositionList &InteractionHeavyWorld::GetHunterSpawnPositions() const
    {
        return mHunterSpawnPositions;
    }

    const InteractionHeavyWorld::PositionList &InteractionHeavyWorld::GetGoblinSpawnPositions() const
    {
        return mGoblinSpawnPositions;
    }

    const InteractionHeavyWorld::PositionList &InteractionHeavyWorld::GetPacingSpawnPositions() const
    {
        return mPacingSpawnPositions;
    }

    double InteractionHeavyWorld::GetScore() const
    {
        return static_cast<double>(mGoldCount * 10 + mStoneCount + mEnemiesKilled * 25 + mPlayerHP);
    }

    std::unordered_map<std::string, double> InteractionHeavyWorld::GetAnalyticsSnapshot() const
    {
        return {
            {"HP", static_cast<double>(mPlayerHP)},
            {"Stone", static_cast<double>(mStoneCount)},
            {"Gold", static_cast<double>(mGoldCount)},
            {"EnemiesKilled", static_cast<double>(mEnemiesKilled)},
            {"Score", GetScore()},
            {"GameOver", mGameOver ? 1.0 : 0.0}};
    }

    bool InteractionHeavyWorld::NearReferencePosition(const WorldPosition &pos,
                                             const WorldPosition &referencePos) const
    {
        const size_t dx = std::abs(static_cast<int>(pos.CellX()) - static_cast<int>(referencePos.CellX()));
        const size_t dy = std::abs(static_cast<int>(pos.CellY()) - static_cast<int>(referencePos.CellY()));
        return (dx + dy) < static_cast<size_t>(kAgentSpawnExclusionDistance);
    }

    bool InteractionHeavyWorld::IsReservedPosition(const WorldPosition &pos) const
    {
        if (pos.SameCell(mStartPosition) || pos.SameCell(mExitPosition))
        {
            return true;
        }

        auto occupies = [&pos](const WorldPosition &p) { return pos.SameCell(p); };

        return std::any_of(mHunterSpawnPositions.begin(), mHunterSpawnPositions.end(), occupies)
            || std::any_of(mGoblinSpawnPositions.begin(), mGoblinSpawnPositions.end(), occupies)
            || std::any_of(mPacingSpawnPositions.begin(), mPacingSpawnPositions.end(), occupies);
    }

    std::vector<WorldPosition> InteractionHeavyWorld::CollectValidFloorPositions() const
    {
        std::vector<WorldPosition> validPositions;
        for (size_t y = 0; y < main_grid.GetHeight(); ++y)
        {
            for (size_t x = 0; x < main_grid.GetWidth(); ++x)
            {
                const WorldPosition pos(x, y);
                if (main_grid[pos] == mFloorCellID
                    && !IsReservedPosition(pos)
                    && !NearReferencePosition(pos, mStartPosition)
                    && !NearReferencePosition(pos, mExitPosition))
                {
                    validPositions.push_back(pos);
                }
            }
        }
        return validPositions;
    }

    std::optional<WorldPosition> InteractionHeavyWorld::GetRandomValidFloorPosition() const
    {
        const auto valid = CollectValidFloorPositions();
        if (valid.empty())
        {
            return std::nullopt;
        }

        std::uniform_int_distribution<size_t> dist(0, valid.size() - 1);
        return valid[dist(mRng)];
    }

    WorldPosition InteractionHeavyWorld::GetPlayerPosition() const
    {
        // The player is the only non-combat agent in this world.
        for (const auto &ptr : agent_set)
        {
            if (ptr && !IsCombatAgent(*ptr))
            {
                return ptr->GetLocation().AsWorldPosition();
            }
        }
        return mStartPosition;
    }

    WorldPosition InteractionHeavyWorld::GetOffGridPosition() const
    {
        return WorldPosition(main_grid.GetWidth() + kOffGridPadding,
                             main_grid.GetHeight() + kOffGridPadding);
    }

    // =============================================================================
    // Boulder placement
    // =============================================================================

    void InteractionHeavyWorld::PlaceBoulders(int minBoulders, int maxBoulders)
    {
        auto validPositions = CollectValidFloorPositions();
        if (validPositions.empty())
        {
            return;
        }

        std::uniform_int_distribution<int> countDist(minBoulders, maxBoulders);
        const int target = std::min(countDist(mRng), static_cast<int>(validPositions.size()));

        std::shuffle(validPositions.begin(), validPositions.end(), mRng);
        for (int i = 0; i < target; ++i)
        {
            main_grid[validPositions[i]] = mBoulderCellID;
        }
    }

    // =============================================================================
    // Neighbor helpers
    // =============================================================================

    std::vector<WorldPosition> InteractionHeavyWorld::GetSelfAndNeighbors(
        const WorldPosition &center) const
    {
        std::vector<WorldPosition> cells;
        cells.reserve(5);

        const std::array<WorldPosition, 5> candidates = {
            center, center.Up(), center.Down(), center.Left(), center.Right()};

        for (const auto &pos : candidates)
        {
            if (main_grid.IsValid(pos))
            {
                cells.push_back(pos);
            }
        }
        return cells;
    }

    std::vector<WorldPosition> InteractionHeavyWorld::GetAdjacentNeighbors(
        const WorldPosition &center) const
    {
        std::vector<WorldPosition> cells;
        cells.reserve(4);

        const std::array<WorldPosition, 4> candidates = {
            center.Up(), center.Down(), center.Left(), center.Right()};

        for (const auto &pos : candidates)
        {
            if (main_grid.IsValid(pos))
            {
                cells.push_back(pos);
            }
        }
        return cells;
    }

    // =============================================================================
    // Resource actions
    // =============================================================================

    void InteractionHeavyWorld::PrintInventory() const
    {
        std::cout << "\nCurrent Stats:\n"
                  << "  HP:    " << mPlayerHP << "\n"
                  << "  Stone: " << mStoneCount << "\n"
                  << "  Gold:  " << mGoldCount << "\n"
                  << "  Enemies killed: " << mEnemiesKilled << "\n\n";
    }

    void InteractionHeavyWorld::BreakBoulder(size_t x, size_t y)
    {
        std::uniform_int_distribution<int> stoneDist(kMinBoulderStone, kMaxBoulderStone);
        std::uniform_int_distribution<int> goldDist(kMinGoldStone, kMaxBoulderGold);

        for (const auto &pos : GetAdjacentNeighbors(WorldPosition(x, y)))
        {
            if (main_grid[pos] == mBoulderCellID)
            {
                main_grid[pos] = mMaterialCellID;
                mDroppedLoot[{pos.CellX(), pos.CellY()}] = {stoneDist(mRng), goldDist(mRng)};
                return;
            }
        }
    }

    void InteractionHeavyWorld::Collect(size_t x, size_t y)
    {
        // Collect checks the center cell and all four cardinal neighbors.
        for (const auto &pos : GetSelfAndNeighbors(WorldPosition(x, y)))
        {
            const size_t tile = main_grid[pos];

            if (tile == mMaterialCellID)
            {
                auto it = mDroppedLoot.find({pos.CellX(), pos.CellY()});
                if (it == mDroppedLoot.end())
                {
                    continue;
                }

                mStoneCount += it->second.stone;
                mGoldCount += it->second.gold;
                mDroppedLoot.erase(it);
                main_grid[pos] = mFloorCellID;
                SyncResources();
                return;
            }

            if (tile == mChestCellID)
            {
                mGoldCount += kChestGoldReward;
                main_grid[pos] = mChestOpenCellID;
                SyncResources();
                return;
            }
        }
    }

    void InteractionHeavyWorld::Pay(size_t x, size_t y)
    {
        // Pay checks the center cell and all four cardinal neighbors.
        for (const auto &pos : GetSelfAndNeighbors(WorldPosition(x, y)))
        {
            for (auto &ptr : agent_set)
            {
                if (!ptr)
                {
                    continue;
                }

                auto *goblin = dynamic_cast<GoblinAgent *>(ptr.get());
                if (!goblin)
                {
                    continue;
                }

                if (!ptr->GetLocation().AsWorldPosition().SameCell(pos))
                {
                    continue;
                }

                if (mGoldCount >= static_cast<size_t>(kGoblinGoldCost))
                {
                    mGoldCount -= kGoblinGoldCost;
                    goblin->ClearBlocking();
                    goblin->SetLocation(GetOffGridPosition());
                    std::cout << "The goblin steps aside.\n";
                    SyncResources();
                }
                else
                {
                    std::cout << "You do not have enough gold to pay the goblin. You need "
                              << kGoblinGoldCost << " gold.\n";
                }
                return;
            }
        }

        std::cout << "There is no goblin nearby to pay.\n";
    }

    void InteractionHeavyWorld::ThrowStone(size_t x, size_t y, int dx, int dy)
    {
        if (mStoneCount == 0)
        {
            std::cout << "No stones to throw.\n";
            return;
        }

        const WorldPosition origin(x, y);

        for (int step = 1; step <= kThrowRange; ++step)
        {
            const WorldPosition target(origin.CellX() + dx * step,
                                       origin.CellY() + dy * step);

            if (!main_grid.IsValid(target))
            {
                return;
            }

            const size_t tile = main_grid[target];

            // Solid tiles absorb the projectile.
            if (tile == mWallCellID || tile == mBoulderCellID || tile == mChestCellID)
            {
                return;
            }

            AgentBase *hit = FindLiveCombatAgentAt(target.CellX(), target.CellY());
            if (hit)
            {
                --mStoneCount;
                SyncResources();

                int &hp = GetCombatAgentHP(hit->GetID());
                hp = std::max(0, hp - kThrowDamage);

                std::cout << "Hit " << hit->GetName()
                          << " for " << kThrowDamage
                          << " damage. HP: " << hp << "\n";

                if (hp <= 0)
                {
                    std::cout << hit->GetName() << " defeated.\n";
                    DefeatCombatAgent(*hit);
                }
                return;
            }
        }

        --mStoneCount;
        SyncResources();
        std::cout << "Stone thrown and missed.\n";
    }

    // =============================================================================
    // Combat helpers
    // =============================================================================

    void InteractionHeavyWorld::ApplyEnemyContactDamage(const WorldPosition &playerPos)
    {
        if (mDamagedThisTurn)
        {
            return;
        }

        for (auto &ptr : agent_set)
        {
            if (!ptr || !IsCombatAgent(*ptr) || !IsCombatAgentAlive(*ptr))
            {
                continue;
            }

            const WorldPosition enemyPos = ptr->GetLocation().AsWorldPosition();
            const int dx = std::abs(static_cast<int>(enemyPos.CellX()) - static_cast<int>(playerPos.CellX()));
            const int dy = std::abs(static_cast<int>(enemyPos.CellY()) - static_cast<int>(playerPos.CellY()));

            if (dx + dy == 1)
            {
                mDamagedThisTurn = true;
                mPlayerHP = std::max(0, mPlayerHP - kEnemyContactDamage);
                std::cout << ptr->GetName() << " hit you! Player HP: " << mPlayerHP << "\n";
            }
        }

        // Sync once after all hits are processed.
        SyncResources();

        if (mPlayerHP <= 0)
        {
            EndGame(false);
        }
    }

    int &InteractionHeavyWorld::GetCombatAgentHP(size_t agentId)
    {
        // Emplace with default HP on first access so newly added agents are handled automatically.
        return mCombatAgentHP.emplace(agentId, kHunterDefaultHP).first->second;
    }

    bool InteractionHeavyWorld::IsCombatAgent(const AgentBase &agent) const
    {
        return dynamic_cast<const HunterAgent *>(&agent) != nullptr
            || dynamic_cast<const PacingAgent *>(&agent) != nullptr;
    }

    bool InteractionHeavyWorld::IsCombatAgentAlive(const AgentBase &agent) const
    {
        if (!IsCombatAgent(agent))
        {
            return false;
        }

        const auto it = mCombatAgentHP.find(agent.GetID());
        return (it == mCombatAgentHP.end()) ? true : (it->second > 0);
    }

    AgentBase *InteractionHeavyWorld::FindLiveCombatAgentAt(size_t x, size_t y,
                                                            const AgentBase *ignore)
    {
        const auto found = std::find_if(agent_set.begin(), agent_set.end(),
                                        [&](const auto &ptr)
                                        {
                                            if (!ptr || (ignore && ptr.get() == ignore))
                                            {
                                                return false;
                                            }
                                            if (!IsCombatAgent(*ptr) || !IsCombatAgentAlive(*ptr))
                                            {
                                                return false;
                                            }

                                            const WorldPosition pos = ptr->GetLocation().AsWorldPosition();
                                            return pos.CellX() == x && pos.CellY() == y;
                                        });

        return (found == agent_set.end()) ? nullptr : found->get();
    }

    AgentBase *InteractionHeavyWorld::FindBlockingAgentAt(size_t x, size_t y,
                                                          const AgentBase *ignore)
    {
        const auto found = std::find_if(agent_set.begin(), agent_set.end(),
                                        [&](const auto &ptr)
                                        {
                                            if (!ptr || (ignore && ptr.get() == ignore))
                                            {
                                                return false;
                                            }

                                            // Dead combat agents do not block movement.
                                            if (IsCombatAgent(*ptr) && !IsCombatAgentAlive(*ptr))
                                            {
                                                return false;
                                            }

                                            const WorldPosition pos = ptr->GetLocation().AsWorldPosition();
                                            return pos.CellX() == x && pos.CellY() == y;
                                        });

        return (found == agent_set.end()) ? nullptr : found->get();
    }

    void InteractionHeavyWorld::DefeatCombatAgent(AgentBase &agent)
    {
        mCombatAgentHP[agent.GetID()] = 0;
        agent.SetLocation(GetOffGridPosition());
        ++mEnemiesKilled;
    }

    bool InteractionHeavyWorld::IsEnemyAt(const WorldPosition &pos) const
    {
        for (const auto &ptr : agent_set)
        {
            if (!ptr || !IsCombatAgent(*ptr) || !IsCombatAgentAlive(*ptr))
            {
                continue;
            }

            if (ptr->GetLocation().AsWorldPosition().SameCell(pos))
            {
                return true;
            }
        }
        return false;
    }

    // =============================================================================
    // Resource sync
    // =============================================================================

    void InteractionHeavyWorld::SyncResources()
    {
        SetWorldResourceCount(RESOURCE_HP, mPlayerHP);
        SetWorldResourceCount(RESOURCE_STONE, static_cast<int>(mStoneCount));
        SetWorldResourceCount(RESOURCE_GOLD, static_cast<int>(mGoldCount));

        for (auto &ptr : agent_set)
        {
            if (!ptr)
            {
                continue;
            }

            NotifyInterfaceResources(*ptr);
        }
    }

    void InteractionHeavyWorld::NotifyInterfaceResources(AgentBase &agent) const
    {
        if (!agent.IsInterface())
        {
            return;
        }

        agent.Notify("HP:" + std::to_string(mPlayerHP), "resource");
        agent.Notify("Stone:" + std::to_string(mStoneCount), "resource");
        agent.Notify("Gold:" + std::to_string(mGoldCount), "resource");
    }

    void InteractionHeavyWorld::EndGame(bool won)
    {
        if (mTimerStarted)
        {
            GetTimer().Stop("Game::Session");
            mTimerStarted = false;
        }

        std::vector<Stat> stats = {
            {"Gold", static_cast<double>(mGoldCount)},
            {"Stone", static_cast<double>(mStoneCount)},
            {"Enemies Defeated", static_cast<double>(mEnemiesKilled)},
            {"Remaining HP", static_cast<double>(mPlayerHP)},
            {"Outcome", won ? 1.0 : 0.0}};

        const int worldSize = static_cast<int>(std::max(main_grid.GetWidth(), main_grid.GetHeight()));
        mEndGameHtml = BuildEndGameHtml(
            true,
            GetScore(),
            GetPlaytimeSeconds(),
            stats,
            GetPositionLog(),
            worldSize);

        std::ostringstream panel;
        panel << "Results ready\n"
              << "Score: " << static_cast<long long>(GetScore()) << "\n"
              << "Playtime: " << GetPlaytimeSeconds() << " sec\n"
              << "Gold: " << mGoldCount << "\n"
              << "Stone: " << mStoneCount << "\n"
              << "Enemies Defeated: " << mEnemiesKilled << "\n"
              << "HTML payload generated for UI.";

        for (auto &ptr : agent_set)
        {
            if (!ptr || !ptr->IsInterface())
            {
                continue;
            }

            ptr->Notify("Game over. Endgame HTML generated.", "status");
            ptr->Notify(panel.str(), "panel_text");
        }

        if (won)
        {
            std::cout << "Congratulations! You reached the exit with "
                      << mStoneCount << " stone and " << mGoldCount << " gold!\n";
        }
        else
        {
            std::cout << "You died.\n";
        }
        
        mGameOver = true;
        run_over  = true;
    }

    // =============================================================================
    // DoAction helpers
    // =============================================================================

    bool InteractionHeavyWorld::IsMovementAction(size_t actionId) const
    {
        return actionId == ACTION_REMAIN_STILL
            || actionId == ACTION_MOVE_UP
            || actionId == ACTION_MOVE_DOWN
            || actionId == ACTION_MOVE_LEFT
            || actionId == ACTION_MOVE_RIGHT;
    }

    bool InteractionHeavyWorld::HandleNonMovementAction(AgentBase &agent,
                                                        size_t actionId,
                                                        const WorldPosition &curPos)
    {
        switch (actionId)
        {
        case ACTION_BREAK_BOULDER:
            BreakBoulder(curPos.CellX(), curPos.CellY());
            return true;

        case ACTION_COLLECT:
            Collect(curPos.CellX(), curPos.CellY());
            return true;

        case ACTION_PAY:
            Pay(curPos.CellX(), curPos.CellY());
            return true;

        case ACTION_PRINT_INVENTORY:
            PrintInventory();
            return true;

        case ACTION_THROW_UP:
            ThrowStone(curPos.CellX(), curPos.CellY(), 0, -1);
            return true;

        case ACTION_THROW_DOWN:
            ThrowStone(curPos.CellX(), curPos.CellY(), 0, 1);
            return true;

        case ACTION_THROW_LEFT:
            ThrowStone(curPos.CellX(), curPos.CellY(), -1, 0);
            return true;

        case ACTION_THROW_RIGHT:
            ThrowStone(curPos.CellX(), curPos.CellY(), 1, 0);
            return true;

        default:
            return false;
        }
    }

    std::optional<WorldPosition> InteractionHeavyWorld::ResolveMovementTarget(
        const WorldPosition &curPos, size_t actionId) const
    {
        switch (actionId)
        {
        case ACTION_REMAIN_STILL:
            return curPos;
        case ACTION_MOVE_UP:
            return curPos.Up();
        case ACTION_MOVE_DOWN:
            return curPos.Down();
        case ACTION_MOVE_LEFT:
            return curPos.Left();
        case ACTION_MOVE_RIGHT:
            return curPos.Right();
        default:
            return std::nullopt;
        }
    }

    int InteractionHeavyWorld::HandleMovementAction(AgentBase &agent, size_t actionId,
                                                    const WorldPosition &targetPos)
    {
        if (!main_grid.IsValid(targetPos))
        {
            return false;
        }

        // Helper: notify a combat agent that its move was rejected.
        auto notifyFailedMove = [&]()
        {
            if (!IsCombatAgent(agent))
            {
                return;
            }
            switch (actionId)
            {
            case ACTION_MOVE_UP:
                agent.Notify("up", "action_failed");
                break;
            case ACTION_MOVE_DOWN:
                agent.Notify("down", "action_failed");
                break;
            case ACTION_MOVE_LEFT:
                agent.Notify("left", "action_failed");
                break;
            case ACTION_MOVE_RIGHT:
                agent.Notify("right", "action_failed");
                break;
            default:
                break;
            }
        };

        // Blocked by a solid tile.
        const size_t targetTile = main_grid[targetPos];
        if (targetTile == mWallCellID
            || targetTile == mBoulderCellID
            || targetTile == mChestCellID
            || targetTile == mChestOpenCellID)
        {
            notifyFailedMove();
            return false;
        }

        // Blocked by another agent.
        AgentBase *blocker = FindBlockingAgentAt(targetPos.CellX(), targetPos.CellY(), &agent);
        if (blocker)
        {
            notifyFailedMove();
            // A combat agent blocked by the player still deals contact damage.
            if (IsCombatAgent(agent) && !IsCombatAgent(*blocker))
            {
                ApplyEnemyContactDamage(GetPlayerPosition());
            }
            return false;
        }

        // Move the agent and check for adjacency damage afterwards.
        agent.SetLocation(targetPos);
        ApplyEnemyContactDamage(GetPlayerPosition());

        // Win condition: player steps onto the exit tile.
        if (targetTile == mExitCellID && agent.GetName() == "Player")
        {
            EndGame(true);
        }

        return true;
    }

    int InteractionHeavyWorld::DoAction(AgentBase &agent, size_t actionId)
    {
        if (mGameOver)
        {
            return false;
        }

        // Reset per-turn damage flag at the start of the player's turn.
        if (agent.GetName() == "Player")
        {
            mDamagedThisTurn = false;
        }

        // Start the session timer on the player's first movement.
        if (!mTimerStarted && agent.GetName() == "Player")
        {
            if (IsMovementAction(actionId))
            {
                GetTimer().Start("Game::Session");
                mTimerStarted = true;
            }
        }

        // Dead combat agents do not get turns.
        if (IsCombatAgent(agent))
        {
            GetCombatAgentHP(agent.GetID()); // Ensure HP entry exists.
            if (!IsCombatAgentAlive(agent))
            {
                return false;
            }
        }

        const WorldPosition curPos = agent.GetLocation().AsWorldPosition();

        // Dispatch non-movement actions first; they return immediately on match.
        if (HandleNonMovementAction(agent, actionId, curPos))
        {
            return true;
        }

        // Resolve the target position for movement actions.
        const auto targetPos = ResolveMovementTarget(curPos, actionId);
        if (!targetPos.has_value())
        {
            return false;
        }

        return HandleMovementAction(agent, actionId, *targetPos);
    }

} // namespace cse498
