/**
 * @file InteractionHeavyWorld.hpp
 * @author Truong Phan
 * @author Jose Hernandez
 *
 * @brief World with dungeon movement, resources, inventory, and hunter combat.
 * @note Status: FINAL
 *
 * @citation This world was developed with the help of Claude AI and Copilot. The initial code was
 * generated by Claude, then iteratively refined and expanded by the authors. Refractoring and cleanup
 * was also assisted by Claude. The dungeon layout was designed by the authors using donjon; RPG Tools
 * (https://donjon.bin.sh/) and loaded from a text file.
 */
#pragma once

#include "../core/WorldBase.hpp"
#include "../tools/EndGameScreen.hpp"
#include <map>
#include <optional>
#include <random>
#include <string>
#include <string_view>
#include <vector>

namespace cse498
{

    // =============================================================================
    // InteractionHeavyWorld
    // =============================================================================

    class InteractionHeavyWorld : public WorldBase
    {
    public:
        using PositionList = std::vector<WorldPosition>;

        // -------------------------------------------------------------------------
        // Construction
        // -------------------------------------------------------------------------

        /**
         * @brief Construct the interaction-heavy world and generate the dungeon.
         */
        InteractionHeavyWorld();

        // -------------------------------------------------------------------------
        // Resource getters
        // -------------------------------------------------------------------------

        /**
         * @brief Get the player's stone count.
         * @return Number of stones in inventory.
         */
        constexpr size_t GetStoneCount() const { return mStoneCount; }

        /**
         * @brief Get the player's gold count.
         * @return Number of gold pieces in inventory.
         */
        constexpr size_t GetGoldCount() const { return mGoldCount; }

        /**
         * @brief Get the player's current HP.
         * @return Current player HP.
         */
        constexpr int GetPlayerHP() const { return mPlayerHP; }

        /**
         * @brief Get the most recently generated endgame HTML payload.
         * @return HTML string for the results screen, or empty if the game has not ended yet.
         */
        const std::string &GetEndGameHtml() const { return mEndGameHtml; }

        /**
         * @brief Compute a simple score for the interaction world.
         * @return Aggregate score based on valuables, kills, and remaining HP.
         */
        [[nodiscard]] double GetScore() const override;

        // -------------------------------------------------------------------------
        // Position getters
        // -------------------------------------------------------------------------

        /**
         * @brief Get the player start position loaded from the dungeon map.
         * @return Start position.
         */
        WorldPosition GetStartPosition() const;

        /**
         * @brief Check whether a position is reserved (start, exit, or enemy spawn).
         * @param pos Position to test.
         * @return True if the position is reserved and should not have boulders placed on it.
         */
        bool IsReservedPosition(const WorldPosition &pos) const;

        /**
         * @brief Get a random valid floor position away from the start and reserved cells.
         * @return Random floor position, or std::nullopt if none available.
         */
        [[nodiscard]] std::optional<WorldPosition> GetRandomValidFloorPosition() const;

        /**
         * @brief Collect all valid floor positions.
         * @return Vector of valid floor positions.
         */
        [[nodiscard]] std::vector<WorldPosition> CollectValidFloorPositions() const;

        /**
         * @brief Get hunter spawn positions loaded from the map.
         * @return Read-only vector of hunter spawn positions.
         */
        const PositionList &GetHunterSpawnPositions() const;

        /**
         * @brief Get goblin spawn positions loaded from the map.
         * @return Read-only vector of goblin spawn positions.
         */
        const PositionList &GetGoblinSpawnPositions() const;

        /**
         * @brief Get pacing-enemy spawn positions loaded from the map.
         * @return Read-only vector of pacing-enemy spawn positions.
         */
        const PositionList &GetPacingSpawnPositions() const;

        // -------------------------------------------------------------------------
        // Query helpers
        // -------------------------------------------------------------------------

        /**
         * @brief Check whether a live combat agent occupies a position.
         * @param pos Position to test.
         * @return True if a live combat agent is on that cell.
         */
        bool IsEnemyAt(const WorldPosition &pos) const;

        /**
         * @brief Check whether a position is near a reference position.
         * @param pos Position to test.
         * @param referencePos Reference position for comparison.
         * @return True if the position is within the minimum safe distance of the reference position.
         */
        bool NearReferencePosition(const WorldPosition &pos, const WorldPosition &referencePos) const;

        /**
         * @brief Print the player's current HP and inventory to stdout.
         */
        void PrintInventory() const;

        // -------------------------------------------------------------------------
        // WorldBase overrides
        // -------------------------------------------------------------------------

        /**
         * @brief Execute one action for an agent.
         * @param agent     Agent performing the action.
         * @param actionId  Action ID selected by the agent.
         * @return Non-zero on success, zero on failure.
         */
        int DoAction(AgentBase &agent, size_t actionId) override;

    protected:
        // -------------------------------------------------------------------------
        // Action IDs
        // -------------------------------------------------------------------------

        enum ActionType
        {
            ACTION_REMAIN_STILL = 0,
            ACTION_MOVE_UP,
            ACTION_MOVE_DOWN,
            ACTION_MOVE_LEFT,
            ACTION_MOVE_RIGHT,
            ACTION_COLLECT,
            ACTION_PAY,
            ACTION_THROW_UP,
            ACTION_THROW_DOWN,
            ACTION_THROW_LEFT,
            ACTION_THROW_RIGHT,
            ACTION_BREAK_BOULDER,
            ACTION_PRINT_INVENTORY
        };

        // -------------------------------------------------------------------------
        // Resource slot indices (into the WorldBase resource vector)
        // -------------------------------------------------------------------------

        enum ResourceIndex
        {
            RESOURCE_HP = 0,
            RESOURCE_STONE = 1,
            RESOURCE_GOLD = 2,
            RESOURCE_COUNT = 3
        };

        // =========================================================================
        // Cell-type IDs (assigned during ConfigureCellTypes)
        // =========================================================================

        size_t mWallCellID = 0;
        size_t mFloorCellID = 0;
        size_t mStartCellID = 0;
        size_t mExitCellID = 0;
        size_t mBoulderCellID = 0;
        size_t mChestCellID = 0;
        size_t mMaterialCellID = 0;
        size_t mChestOpenCellID = 0;

        // -------------------------------------------------------------------------
        // WorldBase overrides
        // -------------------------------------------------------------------------

        /**
         * @brief Register all world actions on an agent.
         * @param agent Agent to configure.
         */
        void ConfigAgent(AgentBase &agent) override;

        // =========================================================================
        // Setup helpers
        // =========================================================================

        /**
         * @brief Register all cell types used by this world.
         */
        void ConfigureCellTypes();

        /**
         * @brief Load the dungeon from a text file and place initial boulders.
         */
        void GenerateWorld();

        /**
         * @brief Populate the grid from a vector of text rows.
         * @param dungeonLayout One string per row; each character maps to a cell type.
         */
        void LoadDungeon(const std::vector<std::string> &dungeonLayout);

        // -------------------------------------------------------------------------
        // Internal resource/action handlers
        // -------------------------------------------------------------------------

        /**
         * @brief Place random boulders on valid floor cells away from the start.
         * @param minBoulders Minimum number of boulders to place.
         * @param maxBoulders Maximum number of boulders to place.
         */
        void PlaceBoulders(int minBoulders, int maxBoulders);

        /**
         * @brief Break an adjacent boulder and leave dropped material.
         * @param x Player cell x-coordinate.
         * @param y Player cell y-coordinate.
         */
        void BreakBoulder(size_t x, size_t y);

        /**
         * @brief Collect material or open a chest adjacent to the player.
         * @param x Player cell x-coordinate.
         * @param y Player cell y-coordinate.
         */
        void Collect(size_t x, size_t y);

        /**
         * @brief Pay a nearby goblin one gold to clear its block.
         * @param x Player cell x-coordinate.
         * @param y Player cell y-coordinate.
         */
        void Pay(size_t x, size_t y);

        /**
         * @brief Throw a stone one step at a time in the given direction.
         * @param x Starting cell x-coordinate.
         * @param y Starting cell y-coordinate.
         * @param dx Direction x-delta (-1, 0, or 1).
         * @param dy Direction y-delta (-1, 0, or 1).
         */
        void ThrowStone(size_t x, size_t y, int dx, int dy);

    private:
        // =========================================================================
        // Constants
        // =========================================================================

        static constexpr std::string_view kDungeonMapFile = "source/Worlds/interaction_world_maps/DungeonMapLarge.txt";
        static constexpr int kPlayerStartHP = 100;
        static constexpr int kHunterDefaultHP = 10;
        static constexpr int kThrowDamage = 10;
        static constexpr int kThrowRange = 4;
        static constexpr int kEnemyContactDamage = 1;
        static constexpr int kChestGoldReward = 8;
        static constexpr int kGoblinGoldCost = 10;
        static constexpr int kAgentSpawnExclusionDistance = 6;
        static constexpr int kOffGridPadding = 10;
        
        static constexpr int kMinBoulderStone = 3;
        static constexpr int kMinGoldStone = 1;
        static constexpr int kMaxBoulderStone = 13;
        static constexpr int kMaxBoulderGold = 7;

        static constexpr int kSmallMapMinBoulders = 3;
        static constexpr int kSmallMapMaxBoulders = 5;
        static constexpr int kLargeMapMinBoulders = 75;
        static constexpr int kLargeMapMaxBoulders = 110;

        // =========================================================================
        // Nested types
        // =========================================================================

        /**
         * @brief Resource bundle left on a cell when a boulder is broken.
         */
        struct BoulderDrop
        {
            int stone = 0;
            int gold = 0;
        };

        using LootKey = std::pair<size_t, size_t>;
        using LootMap = std::map<LootKey, BoulderDrop>;

        // =========================================================================
        // Player, combat, and game state
        // =========================================================================

        int mPlayerHP = kPlayerStartHP;
        int mEnemiesKilled = 0;
        bool mDamagedThisTurn = false;
        bool mTimerStarted = false;
        bool mGameOver = false;
        mutable std::mt19937 mRng{std::random_device{}()};
        std::string mEndGameHtml;

        // =========================================================================
        // Inventory and resources
        // =========================================================================

        /// Dropped boulder loot keyed by cell (x, y).
        LootMap mDroppedLoot;

        size_t mStoneCount = 0;
        size_t mGoldCount = 0;

        // =========================================================================
        // Spawn positions
        // =========================================================================

        WorldPosition mStartPosition;
        WorldPosition mExitPosition;
        PositionList mHunterSpawnPositions;
        PositionList mGoblinSpawnPositions;
        PositionList mPacingSpawnPositions;

        // =========================================================================
        // Per-agent combat HP (keyed by agent ID)
        // =========================================================================

        std::map<size_t, int> mCombatAgentHP;

        // =========================================================================
        // DoAction private helpers 
        // =========================================================================

        /**
         * @brief Check whether an action is a movement action.
         * @param actionId Action ID to check.
         * @return True if the action is a movement action, false otherwise.
         */
        bool IsMovementAction(size_t actionId) const;

        /**
         * @brief Dispatch a non-movement action (throw, collect, pay, break, etc.).
         * @param agent    Agent performing the action.
         * @param actionId Action ID to dispatch.
         * @param curPos   Current position of the agent.
         * @return True if the action was a recognised non-movement action (regardless
         *         of whether it succeeded), false if the caller should continue to
         *         movement handling.
         */
        bool HandleNonMovementAction(AgentBase &agent, size_t actionId,
                                     const WorldPosition &curPos);

        /**
         * @brief Compute the target cell for a movement action.
         * @param curPos   Current position of the agent.
         * @param actionId Movement action ID (one of the ACTION_MOVE_* values).
         * @return Resolved target position, or std::nullopt for an unrecognised action.
         */
        [[nodiscard]] std::optional<WorldPosition> ResolveMovementTarget(const WorldPosition &curPos,
                                                           size_t actionId) const;

        /**
         * @brief Execute a validated movement: check collisions, move the agent,
         *        apply contact damage, and test the win condition.
         * @param agent     Agent attempting to move.
         * @param actionId  Movement action ID (used for failure notifications).
         * @param targetPos Pre-validated target position.
         * @return Non-zero on success, zero if movement was blocked.
         */
        int HandleMovementAction(AgentBase &agent, size_t actionId,
                                 const WorldPosition &targetPos);

        // =========================================================================
        // Private helpers — neighborhood queries
        // =========================================================================

        /**
         * @brief Return the center cell and its four orthogonal neighbors, filtered to valid grid positions.
         * @param center The center cell of the neighborhood.
         * @return A vector of valid positions including the center and its cardinal neighbors.
         */
        [[nodiscard]] std::vector<WorldPosition> GetSelfAndNeighbors(const WorldPosition &center) const;

        /**
         * @brief Return the four orthogonal neighbors of a cell only (excludes center), filtered to valid grid positions.
         * @param center The cell whose neighbors are requested.
         * @return A vector of valid positions for the cardinal neighbors of the center cell, excluding the center itself.
         */
        [[nodiscard]] std::vector<WorldPosition> GetAdjacentNeighbors(const WorldPosition &center) const;

        // =========================================================================
        // Private combat helpers
        // =========================================================================

        /**
         * @brief Get (or lazily create) mutable HP storage for a combat agent.
         * @param agentId Combat agent ID.
         * @return Reference to that agent's HP.
         */
        int &GetCombatAgentHP(size_t agentId);

        /**
         * @brief Check whether an agent participates in combat (hunter or pacing).
         * @param agent Agent to test.
         * @return True if the agent is a HunterAgent or PacingAgent.
         */
        bool IsCombatAgent(const AgentBase &agent) const;

        /**
         * @brief Check whether a combat agent is still alive.
         * @param agent Combat agent to test.
         * @return True if the agent has HP remaining.
         */
        bool IsCombatAgentAlive(const AgentBase &agent) const;

        /**
         * @brief Find a live combat agent at a grid cell.
         * @param x      Cell x-coordinate.
         * @param y      Cell y-coordinate.
         * @param ignore Optional agent to skip during the search.
         * @return Pointer to the agent, or nullptr if none found.
         */
        AgentBase *FindLiveCombatAgentAt(size_t x, size_t y,
                                         const AgentBase *ignore = nullptr);

        /**
         * @brief Find any agent that would block movement into a cell.
         * @param x      Cell x-coordinate.
         * @param y      Cell y-coordinate.
         * @param ignore Optional agent to skip during the search.
         * @return Pointer to the blocking agent, or nullptr if none found.
         */
        AgentBase *FindBlockingAgentAt(size_t x, size_t y,
                                       const AgentBase *ignore = nullptr);

        /**
         * @brief Return the current player position, or the start position as a fallback.
         */
        [[nodiscard]] WorldPosition GetPlayerPosition() const;

        /**
         * @brief Move a defeated combat agent to a position outside the playable grid.
         * @param agent Defeated combat agent.
         */
        void DefeatCombatAgent(AgentBase &agent);

        /**
         * @brief Return a position safely outside the grid bounds.
         */
        [[nodiscard]] WorldPosition GetOffGridPosition() const;

        /**
         * @brief Apply contact damage to the player for each adjacent live combat agent.
         * @param playerPos Current player position.
         */
        void ApplyEnemyContactDamage(const WorldPosition &playerPos);

        // =========================================================================
        // Private resource sync
        // =========================================================================

        /**
         * @brief Push HP, stone, and gold values into the WorldBase resource vector.
         */
        void SyncResources();

        /**
         * @brief Send the current HUD resources to an interface agent.
         * @param agent Interface agent to notify.
         */
        void NotifyInterfaceResources(AgentBase &agent) const;

        // =========================================================================
        // Private endgame helper
        // =========================================================================

        /**
         * @brief Handle end-of-game logic, including victory vs. defeat and any cleanup.
         * @param won True if the player won, false if defeated.
         */
        void EndGame(bool won);
    };

} // namespace cse498